package com.androidexample.gcm;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Stack;

public class Config {	
	// CONSTANTS
	static String YOUR_SERVER_URL = "http://172.20.144.21:8000";
	static String memId = "1111111";
			//http://172.20.144.32:8000
			//"http://slip-msanatan.rhcloud.com";
			//"http://raduoprescu.comxa.com/register.php";
	// YOUR_SERVER_URL : Server url where you have placed your server files
    // Google project id
    static final String GOOGLE_SENDER_ID = "560765005542";  // Place here your Google project id

    /**
     * Tag used on log messages.
     */
    static final String TAG = "Supermarket Behaviour App";

    static final String DISPLAY_MESSAGE_ACTION =
            "com.androidexample.gcm.DISPLAY_MESSAGE";

    static final String EXTRA_MESSAGE = "message";
    

	static int[] Columns = {10, 30, 50, 70, 90, 110, 130, 150, 170, 190, 210, 230, 250, 270, 290, 310, 330, 350, 370, 390, 410};
	static int[] Lines = {10, 30, 50, 70, 90, 110, 130, 150, 170, 190, 210, 230, 250, 270, 290, 310, 330, 350, 370, 390, 410,
			430, 450, 470, 490, 510, 530, 550, 570, 590, 610, 630, 650, 670, 690, 710, 730, 750, 770, 790, 810};
	
	static int posx = 0;
	static int posy = 0;
	
    static int[][] SUPERMARKET_MAP = {
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    	{0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0},
    };
    
    static Integer current_position;
    static ArrayList<String> shopping_list = new ArrayList<String>(); 
    static Stack SHOPPING_STACK = new Stack();
    static List<String> SHOPPING_CART  = new ArrayList<String>();
    
    static Map<String, Integer > PREVIOUS_SHOPPING = new HashMap<String, Integer >() {{put("Apple", 31);put("Apricot", 24);put("Avocado", 34);put("Banana", 0);put("Breadfruit", 23);put("Bilberry", 0);put("Blackberry", 0);put("Blackcurrant", 0);put("Blueberry", 0);put("Boysenberry", 0);put("Cantaloupe", 0);put("Currant", 42);put("Cherry", 0);put("Cherimoya", 37);
		put("Chili", 26);put("Cloudberry", 49);put("Coconut", 46);put("Damson", 34);put("Date", 29);put("Dragonfruit", 33);put("Durian", 0);put("Elderberry", 29);put("Feijoa", 0);put("Fig", 0);put("Gooseberry", 32);put("Grape", 30);put("Grapefruit", 21);put("Guava", 29);put("Huckleberry", 39);
		put("Honeydew", 41);put("Jackfruit", 31);put("Jambul", 46);put("Jujube", 0);put("Kiwi fruit", 28);put("Kumquat", 0);put("Legume", 0);put("Lemon", 32);put("Lime", 46);put("Loquat", 0);put("Lychee", 44);put("Mango", 0);put("Melon", 21);put("Canary melon", 0);put("Cantaloupe", 26);
		put("Honeydew", 0);put("Watermelon", 0);put("Rock melon", 30);put("Nectarine", 35);put("Nut", 0);put("Orange", 44);put("Clementine (type of orange)", 0);put("Mandarine", 0);put("Tangerine", 0);put("Papaya", 45);put("Passionfruit", 0);put("Peach", 43);put("Pepper", 50);put("Pear", 39);put("Williams pear or Bartlett pear", 49);
		put("Persimmon", 0);put("Physalis", 0);put("Plum/prune (dried plum)", 0);put("Pineapple", 0);put("Pomegranate", 0);put("Pomelo", 0);put("Purple Mangosteen", 33);put("Quince", 0);put("Raspberry", 43);put("Western raspberry (blackcap)", 38);put("Rambutan", 0);put("Redcurrant", 33);put("Salal berry", 46);put("Satsuma", 27);put("Star fruit", 29);
		put("Strawberry", 0);put("Tamarillo", 0);put("Tomato", 0);put("Ugli fruit", 0);put("Watermelon—see melon", 46);put("Artichoke", 0);put("Arugula", 0);put("Asparagus", 27);put("Aubergine", 0);put("Amaranth", 0);put("Legumes", 40);put("Alfalfa sprouts", 28);put("Azuki beans (or adzuki)", 50);put("Bean sprouts", 0);put("Black beans", 23);
		put("Black-eyed peas", 28);put("Borlotti bean", 0);put("Broad beans", 0);put("Chickpeas", 48);put("Green beans", 49);put("Kidney beans", 0);put("Lentils", 0);put("Lima beans or Butter bean", 34);put("Mung beans", 49);put("Navy beans", 0);put("Pinto beans", 0);put("Runner beans", 0);put("Soy beans", 0);put("Peas", 30);put("Mangetout or Snap peas", 0);
		put("Bok choy", 25);put("Broccoflower", 0);put("Broccoli", 24);put("Brussels sprouts", 0);put("Cabbage", 0);put("Calabrese", 27);put("Carrots", 0);put("Cauliflower", 42);put("Celery", 0);put("Chard", 0);put("Collard greens", 27);put("Corn salad", 27);put("Endive", 34);put("Fiddleheads", 43);put("Frisee", 0);
		put("Herbs and spices", 21);put("Anise", 20);put("Basil", 36);put("Caraway", 0);put("Cilantro seeds are Coriander", 22);put("Chamomile", 0);put("Dill", 26);put("Fennel", 23);put("Lavender", 41);put("Lemon Grass", 31);put("Marjoram", 35);put("Oregano", 24);put("Parsley", 50);put("Rosemary", 23);put("Sage", 0);
		put("Thyme", 0);put("Kale", 24);put("Kohlrabi", 0);put("Lettuce Lactuca sativa", 0);put("Maize", 35);put("Mustard greens", 0);put("Nettles", 0);put("New Zealand spinach", 45);put("Okra", 37);put("Onion family", 0);put("Chives", 0);put("Garlic", 0);put("Leek Allium porrum", 30);put("Onion", 0);put("Shallot", 38);
		put("Spring onion", 0);put("Parsley", 28);put("Green pepper and Red pepper", 0);put("Chili pepper", 42);put("Jalapeno", 35);put("Habanero", 0);put("Paprika", 40);put("Tabasco pepper", 43);put("Cayenne pepper", 0);put("Radicchio", 0);put("Rhubarb", 21);put("Root vegetables", 0);put("Beetroot", 47);put("mangel-wurzel", 21);put("Carrot", 43);
		put("Celeriac", 26);put("Daikon", 0);put("Ginger", 40);put("Parsnip", 0);put("Rutabaga", 27);put("Turnip", 0);put("Radish", 50);put("Swede", 0);put("Turnip", 0);put("Wasabi", 38);put("Horseradish", 43);put("White radish", 0);put("Salsify", 44);put("Skirret", 40);put("Spinach", 0);
		put("Topinambur", 0);put("Squashes", 0);put("Acorn squash", 0);put("Butternut squash", 29);put("Banana squash", 0);put("Courgette", 0);put("Cucumber", 0);put("Delicata", 37);put("Gem squash", 48);put("Hubbard squash", 20);put("Marrow", 33);put("Patty pans", 0);put("Pumpkin", 44);put("Spaghetti squash", 49);put("Tat soi", 33);
		put("Tomato", 41);put("Tubers", 43);put("Jicama", 33);put("Jerusalem artichoke", 29);put("Potato", 27);put("Sweet potato", 48);put("Taro", 33);put("Yam", 42);put("Water chestnut", 42);put("Watercress", 42);put("basil", 25);put("bay_leaves", 0);put("chives", 32);put("coriander", 34);put("dill", 0);
		put("galangal", 23);put("kaffir_lime_leaves", 48);put("marjoram", 43);put("mint", 0);put("oregano", 33);put("parsley", 34);put("rosemary", 43);put("sage", 23);put("thyme", 20);put("bacon", 39);put("chorizo", 0);put("dips", 0);put("feta_cheese", 0);put("frankfurts", 0);put("ham", 35);
		put("Jarlsberg_cheese", 48);put("olives", 48);put("pate", 0);put("ricotta_cheese", 25);put("salami", 0);put("bread_rolls", 21);put("bread_loaf", 31);put("bread_stick", 45);put("cakes", 0);put("crumpets", 50);put("hot_dog_rolls", 0);put("muffins", 48);put("pikelets", 0);put("wraps", 0);put("baked_beans", 24);
		put("spaghetti", 25);put("breakfast_cereals", 42);put("canned_fish", 26);put("canned_meats", 50);put("canned_vegetables", 28);put("cat_litter", 0);put("chips", 21);put("chocolates", 33);put("coffee", 0);put("cordial", 40);put("cornflour", 20);put("dried_fruit", 0);put("dried_herbs/spices", 41);put("flea_treatments", 0);put("flour,_plain", 38);
		put("flour,_self-raising", 41);put("foil", 28);put("fruit_juice", 28);put("gravies", 0);put("honey", 0);put("hot_chocolate", 31);put("ice_cream cones", 32);put("ice_cream topping", 0);put("indian_foods", 25);put("jam", 41);put("jelly", 29);put("mayonnaise", 0);put("mexican_foods", 21);put("Milo", 21);put("mineral_water", 42);
		put("noodles", 0);put("nuts", 29);put("oils", 39);put("pasta", 41);put("pasta_sauce", 32);put("peanut_butter", 0);put("pet_food", 20);put("plastic_wrap", 0);put("popcorn", 35);put("rice", 29);put("salad_dressings", 42);put("savoury_crackers", 0);put("sesame_oil", 20);put("soft_drinks", 25);put("soup", 40);
		put("soy_sauce", 0);put("stocks", 35);put("sugar", 31);put("sweet_biscuits", 0);put("sweet_chilli sauce", 25);put("tea", 39);put("tinned_fruit", 0);put("tomato_paste", 50);put("tomato_sauce", 0);put("Vegemite", 31);put("vinegar", 0);put("water", 50);put("beef", 0);put("chicken", 23);put("lamb", 0);
		put("mince", 0);put("pork", 0);put("sausages", 0);put("veal", 0);put("butter/margarine", 25);put("cheese", 0);put("cream", 46);put("custard", 0);put("eggs", 0);put("milk", 0);put("sour cream", 33);put("soy_milk", 24);put("tofu", 49);put("yoghurt", 26);put("chips", 30);
		put("desserts", 36);put("fish", 0);put("ice_cream", 23);put("meals", 49);put("pastry", 29);put("pies", 0);put("pizza", 26);put("poultry", 26);put("snacks", 0);put("vegetables", 0);put("conditioner", 25);put("condoms", 26);put("cotton_balls", 49);put("cotton_tips", 0);put("dental_floss", 30);
		put("deodorants", 0);put("first_aid", 0);put("insect_repellent", 38);put("mouthwash", 0);put("other_hair_care", 0);put("panty_liners", 0);put("shampoo", 24);put("shavers", 27);put("skin_care", 0);put("shaving_cream", 30);put("soap", 0);put("sunscreen", 40);put("tampons", 47);put("tissues", 29);put("toilet_paper", 42);
		put("toothbrush", 25);put("toothpaste", 35);put("air_fresheners", 24);put("bathroom_cleaners", 33);put("batteries", 0);put("dishwashing_detergents", 29);put("disinfectants", 38);put("floor_cleaners", 20);put("furniture_cleaners", 0);put("garbage_bags", 29);put("kitchen_cleaners", 33);put("laundry_needs", 45);put("light_globes", 0);put("paper_towels", 0);put("pest_control", 0);
		put("rubber_gloves", 38);put("scourers", 27);put("shoe_care", 20);put("sponges", 36);put("starch/fabric_care", 37);put("stationery", 39);put("toilet_cleaners", 20);put("window_cleaners", 40);put("bath", 0);put("bottles_and_nursing", 0);put("creams", 0);put("food_and_formula", 0);put("medicine", 34);put("nappies", 0);put("nappy_wipes", 0);
		put("Absinthe", 28);put("Akvavit", 25);put("Applejack", 47);put("Arak", 39);put("Arrack", 0);put("Awamori", 46);put("Baijiu", 32);put("Borovicka", 47);put("Cachaça", 0);put("Gin", 0);put("Damson gin", 0);put("Sloe gin", 32);put("Horilka", 23);put("Kaoliang", 29);put("Maotai", 41);
		put("Metaxa", 0);put("Mezcal", 0);put("Neutral grain spirit", 33);put("Ogogoro", 0);put("Ouzo", 46);put("Palinka", 0);put("Pisco", 39);put("Poitín", 21);put("Raki", 36);put("Rakia", 0);put("Slivovitz", 0);put("Rum", 0);put("Shochu", 0);put("Soju", 49);put("Tequila", 49);
		put("Tuica", 24);put("Vodka", 0);put("Whisky", 50);put("Bourbon whiskey", 0);put("Canadian whisky", 0);put("Irish whiskey", 0);put("Japanese whisky", 23);put("Rye whiskey", 0);put("Scotch whisky", 0);put("Tennessee whiskey", 30);put("ManX Spirit", 0);put("Brandy", 23);put("Armagnac", 41);put("Cognac", 0);put("Fruit brandy, Eau-de-vie (French), Schnapps - Obstwasser (German)", 0);
		put("Damassine", 0);put("Himbeergeist", 23);put("Kirsch", 36);put("Poire Williams", 22);put("Williamine", 50);}};    
	    
	static Map<String, Map<String, String> > PRODUCTS_TO_CHARACTERISTICS = new HashMap<String, Map<String,String> >() {{put("Apple", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "2"); put("calories", "49"); put("price", "2.85");}});put("Apricot", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "1"); put("calories", "11"); put("price", "0.86");}});put("Avocado", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "1"); put("calories", "38"); put("price", "4.16");}});put("Banana", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "1"); put("calories", "19"); put("price", "3.57");}});put("Breadfruit", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "7"); put("calories", "48"); put("price", "3.66");}});put("Bilberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "6"); put("calories", "15"); put("price", "4.36");}});put("Blackberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "2"); put("calories", "42"); put("price", "1.91");}});put("Blackcurrant", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "1"); put("calories", "46"); put("price", "4.77");}});put("Blueberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "5"); put("calories", "50"); put("price", "1.79");}});put("Boysenberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "4"); put("calories", "44"); put("price", "4.81");}});put("Cantaloupe", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "7"); put("calories", "27"); put("price", "1.97");}});put("Currant", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "9"); put("calories", "36"); put("price", "2.60");}});put("Cherry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "9"); put("calories", "16"); put("price", "1.08");}});put("Cherimoya", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "17"); put("calories", "47"); put("price", "4.55");}});
		put("Chili", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "19"); put("calories", "37"); put("price", "3.38");}});put("Cloudberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "19"); put("calories", "24"); put("price", "3.59");}});put("Coconut", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "12"); put("calories", "33"); put("price", "2.20");}});put("Damson", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "17"); put("calories", "14"); put("price", "1.42");}});put("Date", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "17"); put("calories", "16"); put("price", "3.05");}});put("Dragonfruit", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "17"); put("calories", "35"); put("price", "3.86");}});put("Durian", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "14"); put("calories", "26"); put("price", "4.64");}});put("Elderberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "15"); put("calories", "27"); put("price", "0.32");}});put("Feijoa", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "18"); put("calories", "17"); put("price", "4.57");}});put("Fig", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "13"); put("calories", "15"); put("price", "0.50");}});put("Gooseberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "14"); put("calories", "46"); put("price", "2.14");}});put("Grape", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "19"); put("calories", "23"); put("price", "3.19");}});put("Grapefruit", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "14"); put("calories", "19"); put("price", "4.25");}});put("Guava", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "11"); put("calories", "49"); put("price", "3.14");}});put("Huckleberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "15"); put("calories", "26"); put("price", "2.57");}});
		put("Honeydew", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "0"); put("posy", "17"); put("calories", "18"); put("price", "4.93");}});put("Jackfruit", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "3"); put("calories", "46"); put("price", "4.55");}});put("Jambul", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "3"); put("calories", "20"); put("price", "1.87");}});put("Jujube", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "4"); put("calories", "22"); put("price", "4.55");}});put("Kiwi fruit", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "6"); put("calories", "24"); put("price", "4.04");}});put("Kumquat", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "4"); put("calories", "35"); put("price", "1.48");}});put("Legume", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "2"); put("calories", "15"); put("price", "2.90");}});put("Lemon", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "2"); put("calories", "39"); put("price", "3.35");}});put("Lime", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "4"); put("calories", "36"); put("price", "3.50");}});put("Loquat", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "4"); put("calories", "48"); put("price", "4.39");}});put("Lychee", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "8"); put("calories", "33"); put("price", "3.43");}});put("Mango", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "1"); put("calories", "36"); put("price", "1.46");}});put("Melon", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "9"); put("calories", "17"); put("price", "4.35");}});put("Canary melon", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "2"); put("calories", "14"); put("price", "4.94");}});put("Cantaloupe", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "3"); put("calories", "10"); put("price", "1.40");}});
		put("Honeydew", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "2"); put("calories", "46"); put("price", "4.91");}});put("Watermelon", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "8"); put("calories", "34"); put("price", "3.53");}});put("Rock melon", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "7"); put("calories", "44"); put("price", "0.89");}});put("Nectarine", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "4"); put("calories", "39"); put("price", "0.61");}});put("Nut", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "7"); put("calories", "46"); put("price", "0.48");}});put("Orange", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "2"); put("posy", "19"); put("calories", "13"); put("price", "4.52");}});put("Clementine (type of orange)", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "2"); put("calories", "23"); put("price", "1.86");}});put("Mandarine", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "4"); put("calories", "22"); put("price", "1.19");}});put("Tangerine", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "9"); put("calories", "23"); put("price", "4.25");}});put("Papaya", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "3"); put("calories", "37"); put("price", "3.51");}});put("Passionfruit", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "2"); put("calories", "33"); put("price", "0.68");}});put("Peach", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "7"); put("calories", "15"); put("price", "3.52");}});put("Pepper", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "1"); put("calories", "43"); put("price", "1.07");}});put("Pear", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "1"); put("calories", "34"); put("price", "0.05");}});put("Williams pear or Bartlett pear", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "7"); put("calories", "30"); put("price", "0.51");}});
		put("Persimmon", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "3"); put("calories", "15"); put("price", "0.59");}});put("Physalis", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "9"); put("calories", "35"); put("price", "3.37");}});put("Plum/prune (dried plum)", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "5"); put("calories", "11"); put("price", "3.56");}});put("Pineapple", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "5"); put("calories", "11"); put("price", "1.74");}});put("Pomegranate", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "8"); put("calories", "28"); put("price", "0.91");}});put("Pomelo", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "3"); put("calories", "13"); put("price", "1.05");}});put("Purple Mangosteen", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "9"); put("calories", "50"); put("price", "3.49");}});put("Quince", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "6"); put("calories", "21"); put("price", "1.66");}});put("Raspberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "8"); put("calories", "11"); put("price", "3.70");}});put("Western raspberry (blackcap)", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "8"); put("calories", "15"); put("price", "4.27");}});put("Rambutan", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "1"); put("calories", "20"); put("price", "2.85");}});put("Redcurrant", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "2"); put("calories", "39"); put("price", "0.73");}});put("Salal berry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "7"); put("calories", "25"); put("price", "3.09");}});put("Satsuma", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "1"); put("calories", "17"); put("price", "3.31");}});put("Star fruit", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "2"); put("calories", "43"); put("price", "0.12");}});
		put("Strawberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "13"); put("calories", "19"); put("price", "1.83");}});put("Tamarillo", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "11"); put("calories", "48"); put("price", "1.07");}});put("Tomato", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "17"); put("calories", "35"); put("price", "2.80");}});put("Ugli fruit", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "14"); put("calories", "41"); put("price", "3.62");}});put("Watermelon—see melon", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "4"); put("posy", "18"); put("calories", "17"); put("price", "3.33");}});put("Artichoke", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "1"); put("calories", "18"); put("price", "0.88");}});put("Arugula", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "7"); put("calories", "34"); put("price", "4.94");}});put("Asparagus", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "5"); put("calories", "26"); put("price", "0.18");}});put("Aubergine", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "2"); put("calories", "14"); put("price", "4.43");}});put("Amaranth", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "5"); put("calories", "23"); put("price", "3.98");}});put("Legumes", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "1"); put("calories", "27"); put("price", "3.67");}});put("Alfalfa sprouts", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "7"); put("calories", "23"); put("price", "1.74");}});put("Azuki beans (or adzuki)", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "6"); put("calories", "24"); put("price", "4.53");}});put("Bean sprouts", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "8"); put("calories", "19"); put("price", "3.21");}});put("Black beans", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "6"); put("calories", "48"); put("price", "1.04");}});
		put("Black-eyed peas", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "6"); put("calories", "35"); put("price", "4.36");}});put("Borlotti bean", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "1"); put("calories", "48"); put("price", "1.84");}});put("Broad beans", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "6"); put("calories", "12"); put("price", "1.79");}});put("Chickpeas", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "8"); put("calories", "50"); put("price", "0.29");}});put("Green beans", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "7"); put("calories", "26"); put("price", "4.00");}});put("Kidney beans", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "3"); put("calories", "44"); put("price", "0.22");}});put("Lentils", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "1"); put("calories", "16"); put("price", "2.56");}});put("Lima beans or Butter bean", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "8"); put("calories", "22"); put("price", "0.46");}});put("Mung beans", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "6"); put("posy", "7"); put("calories", "30"); put("price", "0.93");}});put("Navy beans", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "13"); put("calories", "18"); put("price", "3.32");}});put("Pinto beans", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "13"); put("calories", "41"); put("price", "2.57");}});put("Runner beans", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "15"); put("calories", "33"); put("price", "1.14");}});put("Soy beans", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "17"); put("calories", "46"); put("price", "0.20");}});put("Peas", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "14"); put("calories", "37"); put("price", "2.74");}});put("Mangetout or Snap peas", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "11"); put("calories", "18"); put("price", "3.89");}});
		put("Bok choy", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "14"); put("calories", "20"); put("price", "0.50");}});put("Broccoflower", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "13"); put("calories", "41"); put("price", "0.64");}});put("Broccoli", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "13"); put("calories", "19"); put("price", "2.56");}});put("Brussels sprouts", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "18"); put("calories", "44"); put("price", "1.32");}});put("Cabbage", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "15"); put("calories", "40"); put("price", "1.97");}});put("Calabrese", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "12"); put("calories", "20"); put("price", "4.70");}});put("Carrots", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "13"); put("calories", "50"); put("price", "2.38");}});put("Cauliflower", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "15"); put("calories", "19"); put("price", "3.72");}});put("Celery", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "11"); put("calories", "43"); put("price", "0.76");}});put("Chard", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "6"); put("posy", "16"); put("calories", "40"); put("price", "0.64");}});put("Collard greens", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "8"); put("posy", "5"); put("calories", "11"); put("price", "1.81");}});put("Corn salad", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "8"); put("posy", "3"); put("calories", "10"); put("price", "4.76");}});put("Endive", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "8"); put("posy", "3"); put("calories", "43"); put("price", "4.76");}});put("Fiddleheads", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "18"); put("calories", "39"); put("price", "0.75");}});put("Frisee", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "19"); put("calories", "33"); put("price", "1.33");}});
		put("Herbs and spices", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "11"); put("calories", "21"); put("price", "3.08");}});put("Anise", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "11"); put("calories", "29"); put("price", "1.32");}});put("Basil", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "16"); put("calories", "50"); put("price", "0.61");}});put("Caraway", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "19"); put("calories", "21"); put("price", "4.52");}});put("Cilantro seeds are Coriander", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "12"); put("calories", "35"); put("price", "0.54");}});put("Chamomile", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "11"); put("calories", "23"); put("price", "2.03");}});put("Dill", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "12"); put("calories", "15"); put("price", "3.76");}});put("Fennel", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "15"); put("calories", "21"); put("price", "0.64");}});put("Lavender", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "15"); put("calories", "47"); put("price", "1.95");}});put("Lemon Grass", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "13"); put("calories", "37"); put("price", "4.88");}});put("Marjoram", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "17"); put("calories", "34"); put("price", "0.06");}});put("Oregano", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "14"); put("calories", "48"); put("price", "2.39");}});put("Parsley", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "15"); put("calories", "18"); put("price", "1.61");}});put("Rosemary", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "18"); put("calories", "27"); put("price", "3.63");}});put("Sage", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "15"); put("calories", "35"); put("price", "3.79");}});
		put("Thyme", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "12"); put("calories", "29"); put("price", "1.19");}});put("Kale", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "12"); put("calories", "25"); put("price", "1.38");}});put("Kohlrabi", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "8"); put("posy", "19"); put("calories", "31"); put("price", "4.21");}});put("Lettuce Lactuca sativa", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "3"); put("calories", "44"); put("price", "1.31");}});put("Maize", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "7"); put("calories", "22"); put("price", "2.04");}});put("Mustard greens", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "9"); put("calories", "26"); put("price", "1.23");}});put("Nettles", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "8"); put("calories", "15"); put("price", "3.15");}});put("New Zealand spinach", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "6"); put("calories", "25"); put("price", "3.53");}});put("Okra", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "3"); put("calories", "45"); put("price", "0.84");}});put("Onion family", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "7"); put("calories", "18"); put("price", "4.98");}});put("Chives", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "4"); put("calories", "39"); put("price", "3.54");}});put("Garlic", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "8"); put("calories", "39"); put("price", "3.83");}});put("Leek Allium porrum", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "4"); put("calories", "26"); put("price", "2.05");}});put("Onion", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "1"); put("calories", "42"); put("price", "4.76");}});put("Shallot", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "6"); put("calories", "26"); put("price", "3.51");}});
		put("Spring onion", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "1"); put("calories", "13"); put("price", "2.73");}});put("Parsley", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "2"); put("calories", "33"); put("price", "1.61");}});put("Green pepper and Red pepper", new HashMap<String,String>(){{ put("category", "FRUITS"); put("posx", "10"); put("posy", "9"); put("calories", "48"); put("price", "4.72");}});put("Chili pepper", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "18"); put("calories", "27"); put("price", "0.29");}});put("Jalapeno", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "14"); put("calories", "30"); put("price", "0.26");}});put("Habanero", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "14"); put("calories", "12"); put("price", "2.66");}});put("Paprika", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "12"); put("calories", "29"); put("price", "1.90");}});put("Tabasco pepper", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "18"); put("calories", "36"); put("price", "4.27");}});put("Cayenne pepper", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "19"); put("calories", "48"); put("price", "2.70");}});put("Radicchio", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "14"); put("calories", "34"); put("price", "2.61");}});put("Rhubarb", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "19"); put("calories", "29"); put("price", "0.25");}});put("Root vegetables", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "15"); put("calories", "22"); put("price", "2.19");}});put("Beetroot", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "16"); put("calories", "48"); put("price", "2.73");}});put("mangel-wurzel", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "17"); put("calories", "15"); put("price", "2.19");}});put("Carrot", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "12"); put("calories", "43"); put("price", "0.60");}});
		put("Celeriac", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "17"); put("calories", "24"); put("price", "4.08");}});put("Daikon", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "17"); put("calories", "50"); put("price", "1.21");}});put("Ginger", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "18"); put("calories", "24"); put("price", "1.61");}});put("Parsnip", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "15"); put("calories", "46"); put("price", "1.95");}});put("Rutabaga", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "15"); put("calories", "47"); put("price", "4.86");}});put("Turnip", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "10"); put("posy", "19"); put("calories", "10"); put("price", "1.72");}});put("Radish", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "7"); put("calories", "23"); put("price", "4.37");}});put("Swede", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "8"); put("calories", "32"); put("price", "0.60");}});put("Turnip", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "6"); put("calories", "44"); put("price", "0.19");}});put("Wasabi", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "7"); put("calories", "23"); put("price", "3.95");}});put("Horseradish", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "6"); put("calories", "10"); put("price", "0.58");}});put("White radish", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "7"); put("calories", "31"); put("price", "4.38");}});put("Salsify", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "6"); put("calories", "14"); put("price", "1.03");}});put("Skirret", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "7"); put("calories", "13"); put("price", "4.48");}});put("Spinach", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "1"); put("calories", "36"); put("price", "4.89");}});
		put("Topinambur", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "4"); put("calories", "16"); put("price", "1.00");}});put("Squashes", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "4"); put("calories", "49"); put("price", "4.48");}});put("Acorn squash", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "1"); put("calories", "22"); put("price", "1.39");}});put("Butternut squash", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "5"); put("calories", "34"); put("price", "1.54");}});put("Banana squash", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "8"); put("calories", "35"); put("price", "4.23");}});put("Courgette", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "5"); put("calories", "41"); put("price", "1.22");}});put("Cucumber", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "9"); put("calories", "25"); put("price", "4.37");}});put("Delicata", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "9"); put("calories", "23"); put("price", "0.20");}});put("Gem squash", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "2"); put("calories", "10"); put("price", "2.73");}});put("Hubbard squash", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "2"); put("calories", "32"); put("price", "0.50");}});put("Marrow", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "8"); put("calories", "25"); put("price", "0.30");}});put("Patty pans", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "19"); put("calories", "11"); put("price", "4.36");}});put("Pumpkin", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "16"); put("calories", "40"); put("price", "1.83");}});put("Spaghetti squash", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "16"); put("calories", "11"); put("price", "0.24");}});put("Tat soi", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "19"); put("calories", "22"); put("price", "3.79");}});
		put("Tomato", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "16"); put("calories", "47"); put("price", "4.63");}});put("Tubers", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "15"); put("calories", "20"); put("price", "2.75");}});put("Jicama", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "11"); put("calories", "48"); put("price", "3.30");}});put("Jerusalem artichoke", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "18"); put("calories", "32"); put("price", "1.05");}});put("Potato", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "15"); put("calories", "39"); put("price", "3.94");}});put("Sweet potato", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "16"); put("calories", "36"); put("price", "0.29");}});put("Taro", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "15"); put("calories", "25"); put("price", "2.11");}});put("Yam", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "12"); put("calories", "42"); put("price", "4.53");}});put("Water chestnut", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "14"); put("calories", "46"); put("price", "0.29");}});put("Watercress", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "12"); put("posy", "13"); put("calories", "24"); put("price", "3.09");}});put("basil", new HashMap<String,String>(){{ put("category", "HERBS"); put("posx", "14"); put("posy", "6"); put("calories", "50"); put("price", "1.62");}});put("bay_leaves", new HashMap<String,String>(){{ put("category", "HERBS"); put("posx", "14"); put("posy", "2"); put("calories", "32"); put("price", "2.68");}});put("chives", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "13"); put("calories", "45"); put("price", "3.10");}});put("coriander", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "15"); put("calories", "35"); put("price", "0.59");}});put("dill", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "18"); put("calories", "26"); put("price", "4.14");}});
		put("galangal", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "15"); put("calories", "13"); put("price", "4.40");}});put("kaffir_lime_leaves", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "19"); put("calories", "19"); put("price", "0.21");}});put("marjoram", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "14"); put("calories", "18"); put("price", "4.01");}});put("mint", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "16"); put("calories", "44"); put("price", "1.20");}});put("oregano", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "15"); put("calories", "31"); put("price", "3.98");}});put("parsley", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "11"); put("calories", "45"); put("price", "0.79");}});put("rosemary", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "18"); put("calories", "31"); put("price", "1.70");}});put("sage", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "17"); put("calories", "46"); put("price", "3.58");}});put("thyme", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "14"); put("posy", "18"); put("calories", "12"); put("price", "4.15");}});put("bacon", new HashMap<String,String>(){{ put("category", "DELI"); put("posx", "16"); put("posy", "2"); put("calories", "1001"); put("price", "6.08");}});put("chorizo", new HashMap<String,String>(){{ put("category", "DELI"); put("posx", "16"); put("posy", "7"); put("calories", "496"); put("price", "7.65");}});put("dips", new HashMap<String,String>(){{ put("category", "DELI"); put("posx", "16"); put("posy", "4"); put("calories", "1105"); put("price", "7.43");}});put("feta_cheese", new HashMap<String,String>(){{ put("category", "DELI"); put("posx", "16"); put("posy", "3"); put("calories", "939"); put("price", "10.05");}});put("frankfurts", new HashMap<String,String>(){{ put("category", "DELI"); put("posx", "16"); put("posy", "1"); put("calories", "650"); put("price", "8.63");}});put("ham", new HashMap<String,String>(){{ put("category", "DELI"); put("posx", "16"); put("posy", "5"); put("calories", "589"); put("price", "10.99");}});
		put("Jarlsberg_cheese", new HashMap<String,String>(){{ put("category", "DELI"); put("posx", "16"); put("posy", "2"); put("calories", "725"); put("price", "8.58");}});put("olives", new HashMap<String,String>(){{ put("category", "DELI"); put("posx", "16"); put("posy", "8"); put("calories", "874"); put("price", "8.80");}});put("pate", new HashMap<String,String>(){{ put("category", "DELI"); put("posx", "16"); put("posy", "5"); put("calories", "952"); put("price", "9.11");}});put("ricotta_cheese", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "16"); put("posy", "16"); put("calories", "47"); put("price", "2.99");}});put("salami", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "16"); put("posy", "17"); put("calories", "38"); put("price", "4.57");}});put("bread_rolls", new HashMap<String,String>(){{ put("category", "BAKERY"); put("posx", "18"); put("posy", "1"); put("calories", "81"); put("price", "3.11");}});put("bread_loaf", new HashMap<String,String>(){{ put("category", "BAKERY"); put("posx", "18"); put("posy", "6"); put("calories", "119"); put("price", "0.82");}});put("bread_stick", new HashMap<String,String>(){{ put("category", "BAKERY"); put("posx", "18"); put("posy", "6"); put("calories", "62"); put("price", "4.74");}});put("cakes", new HashMap<String,String>(){{ put("category", "BAKERY"); put("posx", "18"); put("posy", "9"); put("calories", "453"); put("price", "0.47");}});put("crumpets", new HashMap<String,String>(){{ put("category", "BAKERY"); put("posx", "18"); put("posy", "5"); put("calories", "373"); put("price", "0.58");}});put("hot_dog_rolls", new HashMap<String,String>(){{ put("category", "BAKERY"); put("posx", "18"); put("posy", "9"); put("calories", "51"); put("price", "0.96");}});put("muffins", new HashMap<String,String>(){{ put("category", "BAKERY"); put("posx", "18"); put("posy", "4"); put("calories", "184"); put("price", "1.25");}});put("pikelets", new HashMap<String,String>(){{ put("category", "BAKERY"); put("posx", "18"); put("posy", "2"); put("calories", "337"); put("price", "3.61");}});put("wraps", new HashMap<String,String>(){{ put("category", "BAKERY"); put("posx", "18"); put("posy", "6"); put("calories", "433"); put("price", "2.82");}});put("baked_beans", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "18"); put("posy", "15"); put("calories", "825"); put("price", "11.54");}});
		put("spaghetti", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "18"); put("posy", "17"); put("calories", "837"); put("price", "9.41");}});put("breakfast_cereals", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "18"); put("posy", "12"); put("calories", "962"); put("price", "7.17");}});put("canned_fish", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "18"); put("posy", "18"); put("calories", "442"); put("price", "5.27");}});put("canned_meats", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "9"); put("calories", "42"); put("price", "3.14");}});put("canned_vegetables", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "4"); put("calories", "21"); put("price", "3.52");}});put("cat_litter", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "4"); put("calories", "33"); put("price", "4.27");}});put("chips", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "5"); put("calories", "29"); put("price", "3.53");}});put("chocolates", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "5"); put("calories", "41"); put("price", "3.91");}});put("coffee", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "3"); put("calories", "37"); put("price", "2.87");}});put("cordial", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "8"); put("calories", "24"); put("price", "0.28");}});put("cornflour", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "3"); put("calories", "43"); put("price", "3.74");}});put("dried_fruit", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "9"); put("calories", "18"); put("price", "3.10");}});put("dried_herbs/spices", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "7"); put("calories", "19"); put("price", "1.80");}});put("flea_treatments", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "6"); put("calories", "36"); put("price", "0.01");}});put("flour,_plain", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "20"); put("posy", "4"); put("calories", "14"); put("price", "1.00");}});
		put("flour,_self-raising", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "20"); put("posy", "19"); put("calories", "162"); put("price", "8.74");}});put("foil", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "20"); put("posy", "16"); put("calories", "579"); put("price", "5.38");}});put("fruit_juice", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "20"); put("posy", "14"); put("calories", "161"); put("price", "6.04");}});put("gravies", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "20"); put("posy", "19"); put("calories", "241"); put("price", "7.22");}});put("honey", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "20"); put("posy", "13"); put("calories", "971"); put("price", "4.92");}});put("hot_chocolate", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "20"); put("posy", "14"); put("calories", "928"); put("price", "8.84");}});put("ice_cream cones", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "20"); put("posy", "13"); put("calories", "458"); put("price", "14.71");}});put("ice_cream topping", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "20"); put("posy", "15"); put("calories", "588"); put("price", "10.00");}});put("indian_foods", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "20"); put("posy", "16"); put("calories", "632"); put("price", "8.83");}});put("jam", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "20"); put("posy", "16"); put("calories", "250"); put("price", "12.02");}});put("jelly", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "22"); put("posy", "4"); put("calories", "31"); put("price", "1.79");}});put("mayonnaise", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "22"); put("posy", "4"); put("calories", "19"); put("price", "1.76");}});put("mexican_foods", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "22"); put("posy", "3"); put("calories", "16"); put("price", "2.09");}});put("Milo", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "22"); put("posy", "5"); put("calories", "23"); put("price", "1.15");}});put("mineral_water", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "22"); put("posy", "8"); put("calories", "32"); put("price", "1.86");}});
		put("noodles", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "22"); put("posy", "2"); put("calories", "38"); put("price", "3.16");}});put("nuts", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "22"); put("posy", "4"); put("calories", "34"); put("price", "2.16");}});put("oils", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "18"); put("calories", "336"); put("price", "4.73");}});put("pasta", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "18"); put("calories", "583"); put("price", "10.69");}});put("pasta_sauce", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "19"); put("calories", "307"); put("price", "13.81");}});put("peanut_butter", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "14"); put("calories", "892"); put("price", "14.12");}});put("pet_food", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "14"); put("calories", "821"); put("price", "14.51");}});put("plastic_wrap", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "17"); put("calories", "798"); put("price", "4.18");}});put("popcorn", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "15"); put("calories", "266"); put("price", "6.16");}});put("rice", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "12"); put("calories", "391"); put("price", "4.40");}});put("salad_dressings", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "16"); put("calories", "767"); put("price", "9.53");}});put("savoury_crackers", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "13"); put("calories", "593"); put("price", "6.72");}});put("sesame_oil", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "11"); put("calories", "700"); put("price", "4.81");}});put("soft_drinks", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "13"); put("calories", "310"); put("price", "12.43");}});put("soup", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "22"); put("posy", "15"); put("calories", "938"); put("price", "5.50");}});
		put("soy_sauce", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "24"); put("posy", "8"); put("calories", "31"); put("price", "4.90");}});put("stocks", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "24"); put("posy", "4"); put("calories", "36"); put("price", "1.82");}});put("sugar", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "24"); put("posy", "7"); put("calories", "46"); put("price", "3.08");}});put("sweet_biscuits", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("posx", "24"); put("posy", "5"); put("calories", "49"); put("price", "2.87");}});put("sweet_chilli sauce", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "24"); put("posy", "19"); put("calories", "123"); put("price", "11.65");}});put("tea", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "24"); put("posy", "18"); put("calories", "850"); put("price", "10.90");}});put("tinned_fruit", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "24"); put("posy", "14"); put("calories", "103"); put("price", "11.14");}});put("tomato_paste", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "24"); put("posy", "15"); put("calories", "187"); put("price", "12.18");}});put("tomato_sauce", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "24"); put("posy", "14"); put("calories", "239"); put("price", "4.56");}});put("Vegemite", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "24"); put("posy", "13"); put("calories", "836"); put("price", "11.41");}});put("vinegar", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "24"); put("posy", "15"); put("calories", "260"); put("price", "15.65");}});put("water", new HashMap<String,String>(){{ put("category", "GROCERY"); put("posx", "24"); put("posy", "12"); put("calories", "309"); put("price", "5.10");}});put("beef", new HashMap<String,String>(){{ put("category", "MEAT"); put("posx", "26"); put("posy", "7"); put("calories", "434"); put("price", "7.48");}});put("chicken", new HashMap<String,String>(){{ put("category", "MEAT"); put("posx", "26"); put("posy", "8"); put("calories", "440"); put("price", "8.75");}});put("lamb", new HashMap<String,String>(){{ put("category", "MEAT"); put("posx", "26"); put("posy", "4"); put("calories", "121"); put("price", "8.07");}});
		put("mince", new HashMap<String,String>(){{ put("category", "MEAT"); put("posx", "26"); put("posy", "2"); put("calories", "157"); put("price", "10.02");}});put("pork", new HashMap<String,String>(){{ put("category", "MEAT"); put("posx", "26"); put("posy", "7"); put("calories", "285"); put("price", "7.03");}});put("sausages", new HashMap<String,String>(){{ put("category", "MEAT"); put("posx", "26"); put("posy", "9"); put("calories", "434"); put("price", "7.88");}});put("veal", new HashMap<String,String>(){{ put("category", "MEAT"); put("posx", "26"); put("posy", "2"); put("calories", "297"); put("price", "11.22");}});put("butter/margarine", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("posx", "26"); put("posy", "12"); put("calories", "939"); put("price", "10.42");}});put("cheese", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("posx", "26"); put("posy", "17"); put("calories", "566"); put("price", "9.07");}});put("cream", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("posx", "26"); put("posy", "19"); put("calories", "958"); put("price", "10.49");}});put("custard", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("posx", "26"); put("posy", "14"); put("calories", "371"); put("price", "11.74");}});put("eggs", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("posx", "26"); put("posy", "19"); put("calories", "746"); put("price", "8.74");}});put("milk", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("posx", "26"); put("posy", "14"); put("calories", "179"); put("price", "10.13");}});put("sour cream", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("posx", "26"); put("posy", "17"); put("calories", "974"); put("price", "9.21");}});put("soy_milk", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("posx", "26"); put("posy", "19"); put("calories", "871"); put("price", "13.18");}});put("tofu", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("posx", "26"); put("posy", "13"); put("calories", "689"); put("price", "6.98");}});put("yoghurt", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("posx", "26"); put("posy", "12"); put("calories", "532"); put("price", "7.51");}});put("chips", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "8"); put("calories", "452"); put("price", "8.71");}});
		put("desserts", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "2"); put("calories", "755"); put("price", "5.50");}});put("fish", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "7"); put("calories", "515"); put("price", "8.57");}});put("ice_cream", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "4"); put("calories", "1126"); put("price", "10.80");}});put("meals", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "2"); put("calories", "810"); put("price", "5.14");}});put("pastry", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "1"); put("calories", "466"); put("price", "5.48");}});put("pies", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "4"); put("calories", "1092"); put("price", "8.87");}});put("pizza", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "3"); put("calories", "641"); put("price", "6.20");}});put("poultry", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "3"); put("calories", "1102"); put("price", "5.72");}});put("snacks", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "2"); put("calories", "445"); put("price", "6.84");}});put("vegetables", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("posx", "28"); put("posy", "1"); put("calories", "493"); put("price", "7.14");}});put("conditioner", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "28"); put("posy", "17"); put("calories", "0"); put("price", "2.59");}});put("condoms", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "28"); put("posy", "16"); put("calories", "0"); put("price", "6.65");}});put("cotton_balls", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "28"); put("posy", "16"); put("calories", "0"); put("price", "18.90");}});put("cotton_tips", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "28"); put("posy", "19"); put("calories", "0"); put("price", "8.37");}});put("dental_floss", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "28"); put("posy", "18"); put("calories", "0"); put("price", "4.93");}});
		put("deodorants", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "28"); put("posy", "14"); put("calories", "0"); put("price", "3.69");}});put("first_aid", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "28"); put("posy", "14"); put("calories", "0"); put("price", "19.38");}});put("insect_repellent", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "28"); put("posy", "18"); put("calories", "0"); put("price", "10.58");}});put("mouthwash", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "28"); put("posy", "12"); put("calories", "0"); put("price", "2.75");}});put("other_hair_care", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "28"); put("posy", "16"); put("calories", "0"); put("price", "17.74");}});put("panty_liners", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "8"); put("calories", "0"); put("price", "20.03");}});put("shampoo", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "4"); put("calories", "0"); put("price", "11.25");}});put("shavers", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "8"); put("calories", "0"); put("price", "8.02");}});put("skin_care", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "5"); put("calories", "0"); put("price", "13.91");}});put("shaving_cream", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "7"); put("calories", "0"); put("price", "17.51");}});put("soap", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "9"); put("calories", "0"); put("price", "6.19");}});put("sunscreen", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "4"); put("calories", "0"); put("price", "18.63");}});put("tampons", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "2"); put("calories", "0"); put("price", "18.12");}});put("tissues", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "3"); put("calories", "0"); put("price", "3.37");}});put("toilet_paper", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "4"); put("calories", "0"); put("price", "14.48");}});
		put("toothbrush", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "3"); put("calories", "0"); put("price", "9.27");}});put("toothpaste", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "30"); put("posy", "11"); put("calories", "0"); put("price", "18.67");}});put("air_fresheners", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "32"); put("posy", "7"); put("calories", "0"); put("price", "20.67");}});put("bathroom_cleaners", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "32"); put("posy", "4"); put("calories", "0"); put("price", "16.14");}});put("batteries", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "32"); put("posy", "1"); put("calories", "0"); put("price", "6.95");}});put("dishwashing_detergents", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "32"); put("posy", "4"); put("calories", "0"); put("price", "7.61");}});put("disinfectants", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "32"); put("posy", "9"); put("calories", "0"); put("price", "14.60");}});put("floor_cleaners", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "32"); put("posy", "2"); put("calories", "0"); put("price", "19.44");}});put("furniture_cleaners", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "32"); put("posy", "2"); put("calories", "0"); put("price", "6.58");}});put("garbage_bags", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "32"); put("posy", "6"); put("calories", "0"); put("price", "12.74");}});put("kitchen_cleaners", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "32"); put("posy", "15"); put("calories", "0"); put("price", "7.75");}});put("laundry_needs", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "32"); put("posy", "19"); put("calories", "0"); put("price", "9.49");}});put("light_globes", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "34"); put("posy", "6"); put("calories", "0"); put("price", "7.56");}});put("paper_towels", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "34"); put("posy", "9"); put("calories", "0"); put("price", "13.84");}});put("pest_control", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "34"); put("posy", "2"); put("calories", "0"); put("price", "14.63");}});
		put("rubber_gloves", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "34"); put("posy", "3"); put("calories", "0"); put("price", "6.84");}});put("scourers", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "34"); put("posy", "3"); put("calories", "0"); put("price", "18.85");}});put("shoe_care", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "34"); put("posy", "3"); put("calories", "0"); put("price", "16.29");}});put("sponges", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("posx", "34"); put("posy", "1"); put("calories", "0"); put("price", "16.34");}});put("starch/fabric_care", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "34"); put("posy", "14"); put("calories", "0"); put("price", "3.20");}});put("stationery", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "34"); put("posy", "14"); put("calories", "0"); put("price", "7.89");}});put("toilet_cleaners", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "34"); put("posy", "16"); put("calories", "0"); put("price", "16.38");}});put("window_cleaners", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("posx", "34"); put("posy", "14"); put("calories", "0"); put("price", "12.20");}});put("bath", new HashMap<String,String>(){{ put("category", "BABY_TODDLER"); put("posx", "36"); put("posy", "8"); put("calories", "0"); put("price", "18.03");}});put("bottles_and_nursing", new HashMap<String,String>(){{ put("category", "BABY_TODDLER"); put("posx", "36"); put("posy", "3"); put("calories", "0"); put("price", "18.94");}});put("creams", new HashMap<String,String>(){{ put("category", "BABY_TODDLER"); put("posx", "36"); put("posy", "8"); put("calories", "0"); put("price", "10.01");}});put("food_and_formula", new HashMap<String,String>(){{ put("category", "BABY_TODDLER"); put("posx", "36"); put("posy", "9"); put("calories", "0"); put("price", "14.04");}});put("medicine", new HashMap<String,String>(){{ put("category", "BABY_TODDLER"); put("posx", "36"); put("posy", "1"); put("calories", "0"); put("price", "8.75");}});put("nappies", new HashMap<String,String>(){{ put("category", "BABY_TODDLER"); put("posx", "36"); put("posy", "7"); put("calories", "0"); put("price", "16.14");}});put("nappy_wipes", new HashMap<String,String>(){{ put("category", "BABY_TODDLER"); put("posx", "36"); put("posy", "3"); put("calories", "0"); put("price", "8.60");}});
		put("Absinthe", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "16"); put("calories", "602"); put("price", "15.45");}});put("Akvavit", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "18"); put("calories", "1036"); put("price", "24.74");}});put("Applejack", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "15"); put("calories", "579"); put("price", "25.58");}});put("Arak", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "12"); put("calories", "488"); put("price", "22.35");}});put("Arrack", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "18"); put("calories", "547"); put("price", "25.82");}});put("Awamori", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "12"); put("calories", "804"); put("price", "17.56");}});put("Baijiu", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "15"); put("calories", "520"); put("price", "23.64");}});put("Borovicka", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "13"); put("calories", "583"); put("price", "17.85");}});put("Cachaça", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "12"); put("calories", "475"); put("price", "23.88");}});put("Gin", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "13"); put("calories", "655"); put("price", "24.04");}});put("Damson gin", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "12"); put("calories", "426"); put("price", "16.59");}});put("Sloe gin", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "18"); put("calories", "1098"); put("price", "16.94");}});put("Horilka", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "12"); put("calories", "1126"); put("price", "15.41");}});put("Kaoliang", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "13"); put("calories", "1063"); put("price", "25.48");}});put("Maotai", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "18"); put("calories", "466"); put("price", "17.46");}});
		put("Metaxa", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "13"); put("calories", "963"); put("price", "24.42");}});put("Mezcal", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "17"); put("calories", "744"); put("price", "15.36");}});put("Neutral grain spirit", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "16"); put("calories", "640"); put("price", "20.08");}});put("Ogogoro", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "15"); put("calories", "1002"); put("price", "23.92");}});put("Ouzo", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "17"); put("calories", "1117"); put("price", "22.38");}});put("Palinka", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "11"); put("calories", "603"); put("price", "22.72");}});put("Pisco", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "15"); put("calories", "938"); put("price", "25.98");}});put("Poitín", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "14"); put("calories", "962"); put("price", "15.85");}});put("Raki", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "18"); put("calories", "1012"); put("price", "17.88");}});put("Rakia", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "16"); put("calories", "888"); put("price", "20.45");}});put("Slivovitz", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "12"); put("calories", "534"); put("price", "16.10");}});put("Rum", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "19"); put("calories", "1061"); put("price", "15.62");}});put("Shochu", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "13"); put("calories", "841"); put("price", "18.77");}});put("Soju", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "18"); put("calories", "845"); put("price", "20.07");}});put("Tequila", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "19"); put("calories", "997"); put("price", "20.88");}});
		put("Tuica", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "11"); put("calories", "963"); put("price", "16.88");}});put("Vodka", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "11"); put("calories", "671"); put("price", "25.41");}});put("Whisky", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "18"); put("calories", "540"); put("price", "19.84");}});put("Bourbon whiskey", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "12"); put("calories", "747"); put("price", "16.52");}});put("Canadian whisky", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "11"); put("calories", "1054"); put("price", "25.86");}});put("Irish whiskey", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "18"); put("calories", "1044"); put("price", "21.90");}});put("Japanese whisky", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "15"); put("calories", "1164"); put("price", "23.34");}});put("Rye whiskey", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "18"); put("calories", "576"); put("price", "20.78");}});put("Scotch whisky", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "17"); put("calories", "966"); put("price", "25.47");}});put("Tennessee whiskey", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "13"); put("calories", "1109"); put("price", "18.23");}});put("ManX Spirit", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "19"); put("calories", "1095"); put("price", "20.76");}});put("Brandy", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "12"); put("calories", "652"); put("price", "21.42");}});put("Armagnac", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "18"); put("calories", "516"); put("price", "25.51");}});put("Cognac", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "11"); put("calories", "1110"); put("price", "22.27");}});put("Fruit brandy, Eau-de-vie (French), Schnapps - Obstwasser (German)", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "19"); put("calories", "1120"); put("price", "18.44");}});
		put("Damassine", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "12"); put("calories", "470"); put("price", "18.58");}});put("Himbeergeist", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "15"); put("calories", "1132"); put("price", "25.44");}});put("Kirsch", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "14"); put("calories", "790"); put("price", "19.99");}});put("Poire Williams", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "19"); put("calories", "754"); put("price", "21.88");}});put("Williamine", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("posx", "36"); put("posy", "12"); put("calories", "404"); put("price", "16.66");}});}};
	
	static String[] PRODUCTS = new String[] {"Apple","Apricot","Avocado","Banana","Breadfruit","Bilberry","Blackberry","Blackcurrant","Blueberry","Boysenberry","Cantaloupe","Currant","Cherry","Cherimoya"
		,"Chili","Cloudberry","Coconut","Damson","Date","Dragonfruit","Durian","Elderberry","Feijoa","Fig","Gooseberry","Grape","Grapefruit","Guava","Huckleberry"
		,"Honeydew","Jackfruit","Jambul","Jujube","Kiwi fruit","Kumquat","Legume","Lemon","Lime","Loquat","Lychee","Mango","Melon","Canary melon","Cantaloupe"
		,"Honeydew","Watermelon","Rock melon","Nectarine","Nut","Orange","Clementine (type of orange)","Mandarine","Tangerine","Papaya","Passionfruit","Peach","Pepper","Pear","Williams pear or Bartlett pear"
		,"Persimmon","Physalis","Plum/prune (dried plum)","Pineapple","Pomegranate","Pomelo","Purple Mangosteen","Quince","Raspberry","Western raspberry (blackcap)","Rambutan","Redcurrant","Salal berry","Satsuma","Star fruit"
		,"Strawberry","Tamarillo","Tomato","Ugli fruit","Watermelon—see melon","Artichoke","Arugula","Asparagus","Aubergine","Amaranth","Legumes","Alfalfa sprouts","Azuki beans (or adzuki)","Bean sprouts","Black beans"
		,"Black-eyed peas","Borlotti bean","Broad beans","Chickpeas","Green beans","Kidney beans","Lentils","Lima beans or Butter bean","Mung beans","Navy beans","Pinto beans","Runner beans","Soy beans","Peas","Mangetout or Snap peas"
		,"Bok choy","Broccoflower","Broccoli","Brussels sprouts","Cabbage","Calabrese","Carrots","Cauliflower","Celery","Chard","Collard greens","Corn salad","Endive","Fiddleheads","Frisee"
		,"Herbs and spices","Anise","Basil","Caraway","Cilantro seeds are Coriander","Chamomile","Dill","Fennel","Lavender","Lemon Grass","Marjoram","Oregano","Parsley","Rosemary","Sage"
		,"Thyme","Kale","Kohlrabi","Lettuce Lactuca sativa","Maize","Mustard greens","Nettles","New Zealand spinach","Okra","Onion family","Chives","Garlic","Leek Allium porrum","Onion","Shallot"
		,"Spring onion","Parsley","Green pepper and Red pepper","Chili pepper","Jalapeno","Habanero","Paprika","Tabasco pepper","Cayenne pepper","Radicchio","Rhubarb","Root vegetables","Beetroot","mangel-wurzel","Carrot"
		,"Celeriac","Daikon","Ginger","Parsnip","Rutabaga","Turnip","Radish","Swede","Turnip","Wasabi","Horseradish","White radish","Salsify","Skirret","Spinach"
		,"Topinambur","Squashes","Acorn squash","Butternut squash","Banana squash","Courgette","Cucumber","Delicata","Gem squash","Hubbard squash","Marrow","Patty pans","Pumpkin","Spaghetti squash","Tat soi"
		,"Tomato","Tubers","Jicama","Jerusalem artichoke","Potato","Sweet potato","Taro","Yam","Water chestnut","Watercress","basil","bay_leaves","chives","coriander","dill"
		,"galangal","kaffir_lime_leaves","marjoram","mint","oregano","parsley","rosemary","sage","thyme","bacon","chorizo","dips","feta_cheese","frankfurts","ham"
		,"Jarlsberg_cheese","olives","pate","ricotta_cheese","salami","bread_rolls","bread_loaf","bread_stick","cakes","crumpets","hot_dog_rolls","muffins","pikelets","wraps","baked_beans"
		,"spaghetti","breakfast_cereals","canned_fish","canned_meats","canned_vegetables","cat_litter","chips","chocolates","coffee","cordial","cornflour","dried_fruit","dried_herbs/spices","flea_treatments","flour,_plain"
		,"flour,_self-raising","foil","fruit_juice","gravies","honey","hot_chocolate","ice_cream cones","ice_cream topping","indian_foods","jam","jelly","mayonnaise","mexican_foods","Milo","mineral_water"
		,"noodles","nuts","oils","pasta","pasta_sauce","peanut_butter","pet_food","plastic_wrap","popcorn","rice","salad_dressings","savoury_crackers","sesame_oil","soft_drinks","soup"
		,"soy_sauce","stocks","sugar","sweet_biscuits","sweet_chilli sauce","tea","tinned_fruit","tomato_paste","tomato_sauce","Vegemite","vinegar","water","beef","chicken","lamb"
		,"mince","pork","sausages","veal","butter/margarine","cheese","cream","custard","eggs","milk","sour cream","soy_milk","tofu","yoghurt","chips"
		,"desserts","fish","ice_cream","meals","pastry","pies","pizza","poultry","snacks","vegetables","conditioner","condoms","cotton_balls","cotton_tips","dental_floss"
		,"deodorants","first_aid","insect_repellent","mouthwash","other_hair_care","panty_liners","shampoo","shavers","skin_care","shaving_cream","soap","sunscreen","tampons","tissues","toilet_paper"
		,"toothbrush","toothpaste","air_fresheners","bathroom_cleaners","batteries","dishwashing_detergents","disinfectants","floor_cleaners","furniture_cleaners","garbage_bags","kitchen_cleaners","laundry_needs","light_globes","paper_towels","pest_control"
		,"rubber_gloves","scourers","shoe_care","sponges","starch/fabric_care","stationery","toilet_cleaners","window_cleaners","bath","bottles_and_nursing","creams","food_and_formula","medicine","nappies","nappy_wipes"
		,"Absinthe","Akvavit","Applejack","Arak","Arrack","Awamori","Baijiu","Borovicka","Cachaça","Gin","Damson gin","Sloe gin","Horilka","Kaoliang","Maotai"
		,"Metaxa","Mezcal","Neutral grain spirit","Ogogoro","Ouzo","Palinka","Pisco","Poitín","Raki","Rakia","Slivovitz","Rum","Shochu","Soju","Tequila"
		,"Tuica","Vodka","Whisky","Bourbon whiskey","Canadian whisky","Irish whiskey","Japanese whisky","Rye whiskey","Scotch whisky","Tennessee whiskey","ManX Spirit","Brandy","Armagnac","Cognac","Fruit brandy, Eau-de-vie (French), Schnapps - Obstwasser (German)"
		,"Damassine","Himbeergeist","Kirsch","Poire Williams","Williamine"};

	static Map<String, Map<String, String> > OFFERS = new HashMap<String, Map<String,String> >() {{put("Boysenberry", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "2.26"); put("discount", "53");}});
		put("Dragonfruit", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "1.20"); put("discount", "69");}});
		put("Honeydew", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "1.23"); put("discount", "75");}});put("Lychee", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "1.06"); put("discount", "69");}});
		put("Orange", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "0.90"); put("discount", "80");}});
		put("Persimmon", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "0.24"); put("discount", "60");}});put("Rambutan", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "0.88"); put("discount", "69");}});
		put("Artichoke", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "0.33"); put("discount", "62");}});
		put("Black-eyed peas", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "3.44"); put("discount", "21");}});put("Pinto beans", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "1.13"); put("discount", "56");}});
		put("Calabrese", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "1.41"); put("discount", "70");}});
		put("Herbs and spices", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "1.57"); put("discount", "49");}});put("Marjoram", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "0.01"); put("discount", "75");}});
		put("Mustard greens", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "0.80"); put("discount", "35");}});
		put("Spring onion", new HashMap<String,String>(){{ put("category", "FRUITS"); put("price", "1.86"); put("discount", "32");}});put("Rhubarb", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "0.19"); put("discount", "23");}});
		put("Turnip", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "0.67"); put("discount", "61");}});
		put("Topinambur", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "0.28"); put("discount", "72");}});put("Marrow", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "0.23"); put("discount", "24");}});
		put("Sweet potato", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "0.17"); put("discount", "40");}});
		put("galangal", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "2.55"); put("discount", "42");}});put("chorizo", new HashMap<String,String>(){{ put("category", "DELI"); put("price", "4.21"); put("discount", "45");}});
		put("bread_rolls", new HashMap<String,String>(){{ put("category", "BAKERY"); put("price", "2.33"); put("discount", "25");}});
		put("spaghetti", new HashMap<String,String>(){{ put("category", "GROCERY"); put("price", "5.83"); put("discount", "38");}});put("cornflour", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "1.80"); put("discount", "52");}});
		put("hot_chocolate", new HashMap<String,String>(){{ put("category", "GROCERY"); put("price", "3.27"); put("discount", "63");}});
		put("noodles", new HashMap<String,String>(){{ put("category", "VEGETABLES"); put("price", "0.70"); put("discount", "78");}});put("salad_dressings", new HashMap<String,String>(){{ put("category", "GROCERY"); put("price", "7.62"); put("discount", "20");}});
		put("tea", new HashMap<String,String>(){{ put("category", "GROCERY"); put("price", "8.07"); put("discount", "26");}});
		put("mince", new HashMap<String,String>(){{ put("category", "MEAT"); put("price", "2.91"); put("discount", "71");}});put("sour cream", new HashMap<String,String>(){{ put("category", "CHILLERDALRY"); put("price", "3.50"); put("discount", "62");}});
		put("pies", new HashMap<String,String>(){{ put("category", "FROZENFOOD"); put("price", "5.41"); put("discount", "39");}});
		put("deodorants", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("price", "2.84"); put("discount", "23");}});put("soap", new HashMap<String,String>(){{ put("category", "PERSONAL"); put("price", "2.91"); put("discount", "53");}});
		put("dishwashing_detergents", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("price", "4.34"); put("discount", "43");}});
		put("rubber_gloves", new HashMap<String,String>(){{ put("category", "HOUSEHOLD"); put("price", "1.57"); put("discount", "77");}});put("creams", new HashMap<String,String>(){{ put("category", "BABY_TODDLER"); put("price", "5.51"); put("discount", "45");}});
		put("Awamori", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("price", "11.77"); put("discount", "33");}});
		put("Metaxa", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("price", "15.38"); put("discount", "37");}});put("Slivovitz", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("price", "3.22"); put("discount", "80");}});
		put("Irish whiskey", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("price", "13.14"); put("discount", "40");}});
		put("Damassine", new HashMap<String,String>(){{ put("category", "ALCOHOL"); put("price", "5.02"); put("discount", "73");}});}};
}